language: sh

env:
  global:
    - CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=On"

matrix:
  include:

    - os: osx
      osx_image: xcode9.1
      env: CMAKE_CONFIGURATION=release BUILD_DIR=build

    - os: osx
      osx_image: xcode9.1
      env: CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug

    - os: linux
      compiler: clang
      env: CMAKE_CONFIGURATION=release BUILD_DIR=build

    - os: linux
      compiler: clang
      env: CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug

    - os: linux
      compiler: gcc
      env:
        - CMAKE_CONFIGURATION=release BUILD_DIR=build
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - cmake
          - g++-5

    - os: linux
      compiler: gcc
      env:
        - CMAKE_CONFIGURATION=debug BUILD_DIR=build-debug
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - cmake
          - g++-5

    - os: windows
      env:
        - CMAKE_GENERATOR_OVERRIDE="Visual Studio 15 2017 Win64"
        - BUILD_DIR=build-debug
        - CMAKE_CONFIGURATION=debug

    - os: windows
      env:
        - CMAKE_GENERATOR_OVERRIDE="Visual Studio 15 2017 Win64"
        - BUILD_DIR=build
        - CMAKE_CONFIGURATION=release

before_script:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH="$PATH:/c/Program Files/CMake/bin"; fi
  - chmod +x ./configure
  - ./configure
  - ./configure $CMAKE_CONFIGURATION

script:
  - cmake --build $BUILD_DIR
  - cmake --build $BUILD_DIR --target test
  - cmake --build $BUILD_DIR --target coverage
